name: drawings
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - cudatoolkit
  - pytorch
  - cudnn
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyter
  - pip
  - tensorboard
  - tqdm
  - pillow
  - opencv
  - scikit-learn 
  - pandas
  - seaborn
  - pip:
     - oyaml
     - clip

